name: DeepSpace
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.11.0
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: deepspace
        path: ./target/DeepSpace.war
    
    #- name: 'Login via Azure CLI'
    #  uses: azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    #- name: Azure WebApp
    #  uses: Azure/webapps-deploy@v2
    #  with:
    #    # Name of the Azure Web App
    #    app-name: azoospring-petclinic
    #    # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
    #    package: .
